finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mundoalado.urls")),
]

mundoalado/urls.py
from django.urls import path
from . import views

app_name = "mundoalado"

urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

mundoalado/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    class Meta:
        db_table = 'mundoalado_user'  # Nombre de tabla personalizado

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='mundoalado_user_groups',  # Cambiar related_name
        blank=True,
        verbose_name='groups',
        help_text='The groups this user belongs to.',
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='mundoalado_user_permissions',  # Cambiar related_name
        blank=True,
        verbose_name='user permissions',
        help_text='Specific permissions for this user.',
    )

class Bird(models.Model):
    ESTADOS_CONSERVACION = [
        ('LC', 'Preocupación menor'),
        ('NT', 'Casi amenazado'),
        ('VU', 'Vulnerable'),
        ('EN', 'En peligro'),
        ('CR', 'En peligro crítico'),
        ('EW', 'Extinto en estado silvestre'),
        ('EX', 'Extinto'),
    ]

    nombre_comun = models.CharField(max_length=255)
    nombre_cientifico = models.CharField(max_length=255, unique=True)
    familia = models.CharField(max_length=100)
    habitat = models.TextField()
    distribucion_geografica = models.TextField()
    tamaño = models.FloatField(help_text="Tamaño promedio en centímetros")
    peso = models.FloatField(help_text="Peso promedio en gramos")
    coloracion = models.TextField()
    dieta = models.CharField(max_length=255)
    comportamiento = models.TextField()
    estado_conservacion = models.CharField(max_length=2, choices=ESTADOS_CONSERVACION, default='LC')
    imagen = models.ImageField(upload_to='pajaros/', blank=True, null=True)
    sonido = models.URLField(blank=True, null=True)
    fecha_descubrimiento = models.DateField(blank=True, null=True)
    autoridad = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.nombre_comun

mundoalado/views.py
from django.contrib.auth.decorators import login_required  # Decorador para requerir inicio de sesión
from django.views.decorators.csrf import csrf_exempt  # Decorador para permitir solicitudes POST sin CSRF
from django.contrib.auth import authenticate, login, logout  # Funciones para autenticar y manejar sesiones de usuario
from django.db import IntegrityError  # Manejo de errores de integridad en la base de datos
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse  # Respuestas HTTP
from django.shortcuts import render, get_object_or_404  # Funciones para renderizar vistas y obtener objetos
from django.urls import reverse  # Función para generar URLs
import json  # Módulo para manejar JSON
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage # Crear páginas en el front
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

from .models import User

""" Main page """
def index(request):
    return render(request, "mundoalado/index.html")


def login_view(request):
    if request.method == "POST":
        # Intentar iniciar sesión
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Verificar si la autenticación fue exitosa
        if user is not None:
            login(request, user)
            return render(request, "mundoalado/index.html")  # Redirigir al índice
        else:
            return render(request, "mundoalado/login.html", {
                "message": "Nombre de usuario y/o contraseña inválidas."  # Mensaje de error
            })
    else:
        return render(request, "mundoalado/login.html")  # Renderizar la vista de inicio de sesión


@login_required
def logout_view(request):
    logout(request)  # Cerrar sesión
    return render(request, "mundoalado/index.html")  # Redirigir al índice


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Asegurarse de que la contraseña coincide con la confirmación
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "mundoalado/register.html", {
                "message": "Las contraseñas deben coincidir."  # Mensaje de error
            })

        if not username or not email or not password or not confirmation:
            return render(request, "mundoalado/register.html", {
                "message": "Debes completar todos los campos"
            })
        
        if len(password) < 8:
            return render(request, "mundoalado/register.html", {
                "message": "La contraseña debe tener al menos 8 caracteres."
            })
        
        try:
            validate_password(password)
        except ValidationError as e:
            return render(request, "mundoalado/register.html", {
                "message": e.messages  # Mostrará las razones del error de validación
            })

        # Intentar crear un nuevo usuario
        try:
            user = User.objects.create_user(username, email, password)
            user.save()  # Guardar el usuario en la base de datos
        except IntegrityError:
            return render(request, "mundoalado/register.html", {
                "message": "Nombre de usuario ya tomado."  # Mensaje de error
            })
        login(request, user)  # Iniciar sesión con el nuevo usuario
        return render(request, "mundoalado/index.html")  # Redirigir al índice
    else:
        return render(request, "mundoalado/register.html")  # Renderizar la vista de registro

mundoalado/templates/mundoalado/index.html
{% extends 'mundoalado/layout.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block body %}

{% endblock %}

mundoalado/templates/mundoalado/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Mundo Alado{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="{% static 'index.js' %}">
    </head>
    <body>  
        <nav class="upper-bar">
            <ul class="nav-links">
                <li class="link">
                    <a href="#">All birds</a>
                </li>
                <li class="link">
                    <a href="#">Find birds</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="link">
                        <a href="{% url 'mundoalado:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="link">
                        <a href="{% url 'mundoalado:login' %}">Login</a>
                    </li>
                    <li class="link">
                        <a href="{% url 'mundoalado:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </nav>

        {% block body %}
            <div  class="logo-container">
                <img src="{% static 'images/logo-mundo-alado.jpeg' %}" alt="Logo Mundo Alado" class="logo-img">
            </div>                
        {% endblock %}
        {% block script %}{% endblock %}
    </body>
</html>

mundoalado/templates/mundoalado/login.html
{% extends "mundoalado/layout.html" %}

{% block body %}

    <h2 class="principal-title">Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'mundoalado:login' %}" method="post">
        {% csrf_token %}
        
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="submit-button" type="submit" value="Login">
    </form>
    <p></p>
    Don't have an account? <a class="submit-button" href="{% url 'mundoalado:register' %}">Register here.</a>

{% endblock %}

mundoalado/templates/mundoalado/register.html
{% extends "mundoalado/layout.html" %}

{% block body %}

    <h2 class="principal-title">Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'mundoalado:register' %}" method="post">
        {% csrf_token %}
        
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="submit-button" type="submit" value="Register">
    </form>
    <p></p>
    Already have an account? <a class="submit-button" href="{% url 'mundoalado:login' %}">Log In</a>

{% endblock %}